.CSEG
.ORG 0X10
.EQU INPUT_PORT = 0X40
.EQU OUTPUT_PORT = 0X41


IN R1,INPUT_PORT	;INPUT VALUE TO R1 FROM INPUT PORT (USER SPECIFIES WHICH NOTE THEY WANT)		
OUT R1,OUTPUT_PORT	;OUTPUT VALUE R1 TO OUTPUT PORT (OUTPUTS THE CHOSEN CASE)
CALL WAIT			;CALLING WAIT FUNCTION TO LET THE NOTE RUN (WAIT FOR .5 SEC TO LET THE NOTE RUN)

WAIT:
LOOP1: 	MOV R4,0X47

LOOP2:	MOV R5,0X48

LOOP3:	ADD R5,0X01
		BRCC LOOP3	;iterate through loop 3

		ADD R4,0X01
		BRCC LOOP2	;iterate through loop 2

		ADD R3,0x01
		BRCC LOOP1	;iterate through loop 1
