# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/aaron/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-18280-DESKTOP-U7QLGT0/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Documents/DigitalDesign/CPE233/RAT/RAT.cache/wt [current_project]
set_property parent.project_path D:/Documents/DigitalDesign/CPE233/RAT/RAT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Documents/DigitalDesign/CPE233/RAT/RAT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST1.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/RAT5.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/SIM1.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/ReverseEngineerRAT.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST1_SIM.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST2_SIM.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST2.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST3.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST4.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST6.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST5.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TESTALL.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TESTALL_SIM.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TEST8.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TEST9.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TEST10.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST9_SIM.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TEST11.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TEST12.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/TEST7.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TEST10_SIM.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/INTTEST.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/INTTEST_SIM.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/Final.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/KeyboardTest.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TESTER.mem
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/CPE233/TESTY.mem
}
read_verilog -library xil_defaultlib -sv {
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/ALU.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/BCD.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/C.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/CathodeDriver.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/ClockDivider.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/Control_Unit.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/Flags.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/FrequencyDecoder.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/I.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/KeyboardDriver.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/Mux2.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/Mux4.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/ProgRom.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/ProgramCounter.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/RAT_MCU.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/REG_FILE.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/SCRATCH_RAM.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/SCR_ADDR_MUX.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/SHAD_C.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/SHAD_Z.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/SevSegDisp.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/Speaker.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/StackPointer.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/imports/new/Z.sv
  D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/sources_1/new/RAT_WRAPPER.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/constrs_1/imports/new/BasysConstraints.xdc
set_property used_in_implementation false [get_files D:/Documents/DigitalDesign/CPE233/RAT/RAT.srcs/constrs_1/imports/new/BasysConstraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RAT_WRAPPER -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RAT_WRAPPER.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RAT_WRAPPER_utilization_synth.rpt -pb RAT_WRAPPER_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
